// import React from 'react';
// import { useGLTF, useTexture } from '@react-three/drei';

// const Room = (props) => {
//   const { nodes, materials } = useGLTF('/models/hacker-room.glb');

//   const monitortxt = useTexture('textures/desk/monitor.png');
//   const screenTxt = useTexture('textures/desk/screen.png');

//   return (
//     <group {...props} dispose={null}>
//       <mesh geometry={nodes.screen_screens_0.geometry} material={materials.screens}>
//         <meshMatcapMaterial map={screenTxt} />
//       </mesh>
//       <mesh geometry={nodes.screen_glass_glass_0.geometry} material={materials.glass} />
//       <mesh geometry={nodes.table_table_mat_0_1.geometry} material={materials.table_mat} />
//       <mesh geometry={nodes.table_table_mat_0_2.geometry} material={materials.computer_mat}>
//         <meshMatcapMaterial map={monitortxt} />
//       </mesh>
//       <mesh geometry={nodes.table_table_mat_0_3.geometry} material={materials.server_mat} />
//       <mesh geometry={nodes.table_table_mat_0_4.geometry} material={materials.vhsPlayer_mat} />
//       <mesh geometry={nodes.table_table_mat_0_5.geometry} material={materials.stand_mat} />
//       <mesh geometry={nodes.table_table_mat_0_6.geometry} material={materials.mat_mat} />
//       <mesh geometry={nodes.table_table_mat_0_7.geometry} material={materials.arm_mat} />
//       <mesh geometry={nodes.table_table_mat_0_8.geometry} material={materials.tv_mat}>
//         <meshMatcapMaterial map={monitortxt} />
//       </mesh>
//       <mesh geometry={nodes.table_table_mat_0_9.geometry} material={materials.cables_mat} />
//       <mesh geometry={nodes.table_table_mat_0_10.geometry} material={materials.props_mat} />
//       <mesh geometry={nodes.table_table_mat_0_11.geometry} material={materials.ground_mat} />
//       <mesh geometry={nodes.table_table_mat_0_12.geometry} material={materials.key_mat} />
//     </group>
//   );
// }
// useGLTF.preload('/models/hacker-room.glb');
// export default Room;


/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: crimsonfalcon (https://sketchfab.com/crimsonfalcon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/computer-components-4daeb72925d140809bdfd51634a1908e
Title: Computer Components
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Room = (props) => {
  const { nodes, materials } = useGLTF('models/computer_components.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0.262, -0.724, 4.829]} rotation={[-0.364, -0.284, -1.827]} scale={0.5}>
          <group position={[0, -0.009, 0.827]} rotation={[0, 0, Math.PI / 2]} scale={0.035}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['35inch_HDD002_1'].geometry}
              material={materials['HDD.003']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['35inch_HDD002_2'].geometry}
              material={materials['HDD.004']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['35inch_HDD002_3'].geometry}
              material={materials['SATA_connector.000']}
            />
          </group>
          <group position={[0, 0, -0.012]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['35inch_HDD003_1'].geometry}
              material={materials['HDD.001']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['35inch_HDD003_2'].geometry}
              material={materials['HDD.002']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['35inch_HDD003_3'].geometry}
              material={materials['HDD.003']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['35inch_HDD003_4'].geometry}
              material={materials['HDD.004']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['35inch_HDD003_5'].geometry}
              material={materials['HDD.000']}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['35inch_HDD001_1'].geometry}
            material={materials['HDD.004']}
            position={[0, 0, 0.827]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['35inch_HDD004_1'].geometry}
            material={materials['HDD.000']}
            position={[0, 0, 1.465]}
          />
        </group>
        <group position={[-1.4, -2.079, 6.971]} rotation={[-2.872, -0.123, 0.011]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['25inch_SSD_1'].geometry}
            material={materials['SSD.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['25inch_SSD_2'].geometry}
            material={materials['SSD.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['25inch_SSD_3'].geometry}
            material={materials['SSD.000']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['25inch_SSD_4'].geometry}
            material={materials['SATA_connector.000']}
          />
        </group>
        <group position={[-3.463, -3.711, 6.728]} rotation={[0.641, 0.144, -1.347]} scale={0.277}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.CPU_1.geometry}
            material={materials['CPU.000']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.CPU_2.geometry}
            material={materials['CPU.001']}
          />
        </group>
        <group position={[-4.019, 2.992, 6.441]} rotation={[-1.572, -0.588, -0.026]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.PSU_1.geometry}
            material={materials['PSU.000']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.PSU_2.geometry}
            material={materials['PSU.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.PSU_3.geometry}
            material={materials['PSU.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.PSU_4.geometry}
            material={materials['PSU.003']}
          />
        </group>
        <group position={[2.537, 1.917, 8.733]} rotation={[0.014, -0.277, 0.104]} scale={0.585}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.FAN004_1.geometry}
            material={materials['FAN.000']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.FAN004_2.geometry}
            material={materials['FAN.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.FAN004_3.geometry}
            material={materials['FAN.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.FAN003_1.geometry}
            material={materials['FAN.000']}
          />
        </group>
        <group position={[-1.047, -1.372, 9.087]} rotation={[0.121, 0.152, -1.908]}>
          <group position={[0, 0, 0.194]} scale={0.85}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['25inch_HDD001_1'].geometry}
              material={materials['HDD2.5inch.000']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['25inch_HDD001_2'].geometry}
              material={materials['HDD2.5inch.001']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['25inch_HDD001_3'].geometry}
              material={materials['HDD2.5inch.003']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['25inch_HDD001_4'].geometry}
              material={materials['SATA_connector.000']}
            />
          </group>
          <group position={[0, 0, 0.194]} scale={0.85}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['25inch_HDD002_1'].geometry}
              material={materials['HDD2.5inch.000']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['25inch_HDD002_2'].geometry}
              material={materials['HDD2.5inch.001']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['25inch_HDD002_3'].geometry}
              material={materials['HDD2.5inch.002']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['25inch_HDD002_4'].geometry}
              material={materials['HDD2.5inch.003']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['25inch_HDD002_5'].geometry}
              material={materials['HDD2.5inch.004']}
            />
          </group>
          <group position={[0, 0, 0.194]} scale={0.85}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['25inch_HDD003_1'].geometry}
              material={materials['HDD2.5inch.000']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['25inch_HDD003_2'].geometry}
              material={materials['HDD2.5inch.002']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['25inch_HDD003_3'].geometry}
              material={materials['HDD2.5inch.003']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['25inch_HDD003_4'].geometry}
              material={materials['HDD2.5inch.004']}
            />
          </group>
        </group>
        <group
          position={[-1.805, -4.134, 10.372]}
          rotation={[-0.171, -0.249, -0.796]}
          scale={0.277}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.CPU001_1.geometry}
            material={materials['CPU.000']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.CPU001_2.geometry}
            material={materials['CPU.001']}
          />
        </group>
        <group position={[-1.434, -3.906, 14.523]} rotation={[0.305, 0.416, -0.634]} scale={0.277}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.CPU002_1.geometry}
            material={materials['CPU.000']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.CPU002_2.geometry}
            material={materials['CPU.001']}
          />
        </group>
        <group position={[4.615, 1.583, 3.848]} rotation={[3.016, 0.623, 0.449]} scale={0.674}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.FAN000_1.geometry}
            material={materials['FAN.000']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.FAN000_2.geometry}
            material={materials['FAN.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.FAN000_3.geometry}
            material={materials['FAN.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.FAN001_1.geometry}
            material={materials['FAN.000']}
          />
        </group>
        <group position={[-7.949, 2.692, 0.65]} rotation={[1.661, -0.384, -0.217]} scale={0.849}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.PSU001_1.geometry}
            material={materials['PSU.000']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.PSU001_2.geometry}
            material={materials['PSU.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.PSU001_3.geometry}
            material={materials['PSU.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.PSU001_4.geometry}
            material={materials['PSU.003']}
          />
        </group>
        <group position={[-3.162, -0.281, 6.5]} rotation={[2.291, -0.695, 1.136]}>
          <group position={[0, 0, 0.194]} scale={0.85}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['25inch_HDD005_1'].geometry}
              material={materials['HDD2.5inch.000']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['25inch_HDD005_2'].geometry}
              material={materials['HDD2.5inch.002']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['25inch_HDD005_3'].geometry}
              material={materials['HDD2.5inch.003']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['25inch_HDD005_4'].geometry}
              material={materials['HDD2.5inch.004']}
            />
          </group>
          <group position={[0, 0, 0.194]} scale={0.85}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['25inch_HDD004_1'].geometry}
              material={materials['HDD2.5inch.000']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['25inch_HDD004_2'].geometry}
              material={materials['HDD2.5inch.001']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['25inch_HDD004_3'].geometry}
              material={materials['HDD2.5inch.002']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['25inch_HDD004_4'].geometry}
              material={materials['HDD2.5inch.003']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['25inch_HDD004_5'].geometry}
              material={materials['HDD2.5inch.004']}
            />
          </group>
          <group position={[0, 0, 0.194]} scale={0.85}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['25inch_HDD000_1'].geometry}
              material={materials['HDD2.5inch.000']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['25inch_HDD000_2'].geometry}
              material={materials['HDD2.5inch.001']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['25inch_HDD000_3'].geometry}
              material={materials['HDD2.5inch.003']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['25inch_HDD000_4'].geometry}
              material={materials['SATA_connector.000']}
            />
          </group>
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RAM_1.geometry}
          material={materials.material}
          position={[3.315, -2.674, 3.08]}
          rotation={[-0.166, -0.289, 2.038]}
          scale={0.543}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HeatSink_1.geometry}
          material={materials.HeatSink}
          position={[2.316, 0.298, 9.152]}
          rotation={[0.65, 0.25, -0.664]}
          scale={0.513}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RAM001_1.geometry}
          material={materials.material}
          position={[0.858, -4.337, 7.956]}
          rotation={[0.138, 0.408, 0.281]}
          scale={0.543}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RAM002_1.geometry}
          material={materials.material}
          position={[2.266, -3.672, 5.498]}
          rotation={[-0.036, -0.477, 1.312]}
          scale={0.543}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HeatSink001_1.geometry}
          material={materials.HeatSink}
          position={[2.169, -0.029, 12.638]}
          rotation={[-0.055, -1.058, -0.235]}
          scale={[0.513, 0.513, 0.269]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('models/computer_components.glb')

export default Room;
